# Generated by Django 5.1.7 on 2025-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelv3", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnovaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=100)),
                ("f_statistic", models.FloatField()),
                ("p_value", models.FloatField()),
                ("significance", models.BooleanField()),
            ],
        ),
    ]
