# Generated by Django 5.1.7 on 2025-03-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelv3", "0003_anovaresult_pcaresult_delete_anovadata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RandomForestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
