# Generated by Django 5.1.7 on 2025-03-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelv3", "0004_randomforestresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="randomforestresult",
            name="actual_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="randomforestresult",
            name="f1_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="randomforestresult",
            name="macro_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="randomforestresult",
            name="precision",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="randomforestresult",
            name="predicted_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="randomforestresult",
            name="recall",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="randomforestresult",
            name="support",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="randomforestresult",
            name="weighted_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="randomforestresult",
            name="accuracy",
            field=models.FloatField(default=0.0),
        ),
    ]
