# Generated by Django 5.1.7 on 2025-03-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelv3", "0005_randomforestresult_actual_value_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeanMedianModeResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mean_values", models.FloatField(default=0.0)),
                ("median_values", models.FloatField(default=0.0)),
                ("mode_values", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
